/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        magenta: "#C82964",
        burgundy: "#801F53",
        orange: "#EF9752",
        white: "#ffffff",
        black: "#000000",
        secondary: "#d4d3e7",
        "light-secondary": "#F0F0F0",
        "primary-text": "#334155",
        "secondary-text": "#808fa4",
        "light-orange": "#F7CBA8",
      },
      fontFamily: {
        poppins: ["poppins", "sans-serif"],
        "poppins-bold": ["poppins-bold", "sans-serif"],
        "poppins-light": ["poppins-light", "sans-serif"],
        "poppins-semibold": ["poppins-semibold", "sans-serif"],
        roboto: ["roboto", "sans-serif"],
        "roboto-bold": ["roboto-bold", "sans-serif"],
        "roboto-light": ["roboto-light", "sans-serif"],
        "roboto-semibold": ["roboto-semibold", "sans-serif"],
        quicksand: ["quicksand", "sans-serif"],
        "quicksand-semibold": ["quicksand-semibold", "sans-serif"],
        "quicksand-bold": ["quicksand-bold", "sans-serif"],
      },
      fontSize: {
        xs: 10,
        sm: 12,
        md: 14,
        lg: 16,
        lgp: 17,
        xl: 20,
        "2xl": 24,
        "3xl": 28,
        "4xl": 32,
        "5xl": 40,
        "6xl": 48,
        "8xl": 54,
        "10xl": 80,
      },
      letterSpacing: {
        1: "0.001em",
        2: "0.0015em",
        3: "0.0025em",
        4: "0.004em",
        5: "0.01em",
        6: "0.05em",
      },
      backgroundImage: {
        "workshop-bg": "url('/assets/images/workshop-card.jpg')",
        "sekelas-bg": "url('/assets/images/sekelas-card.jpg')"
      },
    },
  },
  plugins: [],
};
